### PR TITLE
Added caching

### PR DESCRIPTION
**Pull request by tadywankenobi**
I've added some caching here. I'm not 100% the else statement is working, or is the most efficient way of doing so. Let me know what you think.

### CODE REVIEW

**Comment by tadywankenobi** [comment]
Oh, and I only worked off the width, height and scale in the cached filename. Should be easy enough to add the crop. I just wanted to get it working first.

**Comment by iandevlin** [comment]
Well to be honest if it's not complete I'm not going to merge it.

**Comment by tadywankenobi** [comment]
Yup, fair point. Added.

Noticed a mistake in the height value of the cache file too. Fixed now.

**Comment by tadywankenobi** [comment]
Tested to ensure after creating the file, cache is used at next load. Working as expected.

**Comment by tadywankenobi** [comment]
OK, I'm done. All yours if you want it. Look forward to using it at some point in the near future.

**Comment by iandevlin** [comment]
I'll have a look later although I might not merge the whole thing, only bits of it (if possible) for various reasons.

**Comment by tadywankenobi** [comment]
No worries. No obligation to at all, tis your baby!

**Comment by iandevlin** [comment]
Ok I've added your code and tidied it up in some parts. I didn't merge the request as I didn't want to include the cached image files so it was easier to copy your code.

Thanks!

**Pull request closed without merging**
